// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hyperlane/warp/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState is the state that must be provided at genesis.
type GenesisState struct {
	Params        Params                       `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Tokens        []HypToken                   `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens"`
	RemoteRouters []GenesisRemoteRouterWrapper `protobuf:"bytes,3,rep,name=remote_routers,json=remoteRouters,proto3" json:"remote_routers"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_09202a973c73677a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTokens() []HypToken {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *GenesisState) GetRemoteRouters() []GenesisRemoteRouterWrapper {
	if m != nil {
		return m.RemoteRouters
	}
	return nil
}

// GenesisRemoteRouterWrapper ...
type GenesisRemoteRouterWrapper struct {
	TokenId      uint64       `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	RemoteRouter RemoteRouter `protobuf:"bytes,2,opt,name=remote_router,json=remoteRouter,proto3" json:"remote_router"`
}

func (m *GenesisRemoteRouterWrapper) Reset()         { *m = GenesisRemoteRouterWrapper{} }
func (m *GenesisRemoteRouterWrapper) String() string { return proto.CompactTextString(m) }
func (*GenesisRemoteRouterWrapper) ProtoMessage()    {}
func (*GenesisRemoteRouterWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_09202a973c73677a, []int{1}
}
func (m *GenesisRemoteRouterWrapper) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisRemoteRouterWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisRemoteRouterWrapper.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisRemoteRouterWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisRemoteRouterWrapper.Merge(m, src)
}
func (m *GenesisRemoteRouterWrapper) XXX_Size() int {
	return m.Size()
}
func (m *GenesisRemoteRouterWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisRemoteRouterWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisRemoteRouterWrapper proto.InternalMessageInfo

func (m *GenesisRemoteRouterWrapper) GetTokenId() uint64 {
	if m != nil {
		return m.TokenId
	}
	return 0
}

func (m *GenesisRemoteRouterWrapper) GetRemoteRouter() RemoteRouter {
	if m != nil {
		return m.RemoteRouter
	}
	return RemoteRouter{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "hyperlane.warp.v1.GenesisState")
	proto.RegisterType((*GenesisRemoteRouterWrapper)(nil), "hyperlane.warp.v1.GenesisRemoteRouterWrapper")
}

func init() { proto.RegisterFile("hyperlane/warp/v1/genesis.proto", fileDescriptor_09202a973c73677a) }

var fileDescriptor_09202a973c73677a = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4f, 0xc2, 0x30,
	0x18, 0xc6, 0x57, 0x20, 0x68, 0x0a, 0x98, 0xb8, 0x78, 0x18, 0x18, 0x07, 0xe1, 0xc4, 0x85, 0x36,
	0x60, 0x8c, 0xf1, 0xca, 0xc5, 0x3f, 0x17, 0xcd, 0x34, 0x31, 0xe1, 0x42, 0x0a, 0xbc, 0x19, 0x8b,
	0x6e, 0x6d, 0xda, 0x82, 0xcc, 0xab, 0x5f, 0xc0, 0x8f, 0xc5, 0x91, 0xa3, 0x27, 0x62, 0xe0, 0x8b,
	0x18, 0xba, 0x49, 0x30, 0xe0, 0xed, 0xdd, 0xfa, 0x7b, 0x9e, 0xf7, 0x69, 0x1f, 0x5c, 0x1d, 0xc5,
	0x02, 0xe4, 0x2b, 0x8b, 0x80, 0xbe, 0x31, 0x29, 0xe8, 0xa4, 0x45, 0x7d, 0x88, 0x40, 0x05, 0x8a,
	0x08, 0xc9, 0x35, 0xb7, 0x8f, 0x37, 0x00, 0x59, 0x03, 0x64, 0xd2, 0xaa, 0x9c, 0xed, 0x6a, 0x74,
	0x2c, 0x20, 0x55, 0x54, 0x4e, 0x7c, 0xee, 0x73, 0x33, 0xd2, 0xf5, 0x94, 0xfc, 0xad, 0x2f, 0x10,
	0x2e, 0x5e, 0x27, 0xce, 0x8f, 0x9a, 0x69, 0xb0, 0x2f, 0x71, 0x5e, 0x30, 0xc9, 0x42, 0xe5, 0xa0,
	0x1a, 0x6a, 0x14, 0xda, 0x65, 0xb2, 0xb3, 0x89, 0x3c, 0x18, 0xa0, 0x93, 0x9b, 0x2d, 0xaa, 0x96,
	0x97, 0xe2, 0xf6, 0x15, 0xce, 0x6b, 0xfe, 0x02, 0x91, 0x72, 0x32, 0xb5, 0x6c, 0xa3, 0xd0, 0x3e,
	0xdd, 0x23, 0xbc, 0x89, 0xc5, 0xd3, 0x9a, 0xf9, 0x95, 0x26, 0x02, 0xbb, 0x8b, 0x8f, 0x24, 0x84,
	0x5c, 0x43, 0x4f, 0xf2, 0xb1, 0x06, 0xa9, 0x9c, 0xac, 0xb1, 0x68, 0xee, 0xb1, 0x48, 0xc3, 0x7a,
	0x86, 0xf7, 0x0c, 0xfe, 0x2c, 0x99, 0x10, 0x20, 0x53, 0xd3, 0x92, 0xdc, 0x3a, 0x52, 0xf5, 0x0f,
	0x84, 0x2b, 0xff, 0x6b, 0xec, 0x32, 0x3e, 0x34, 0x21, 0x7a, 0xc1, 0xd0, 0x5c, 0x38, 0xe7, 0x1d,
	0x98, 0xef, 0xdb, 0xa1, 0x7d, 0x87, 0x4b, 0x7f, 0x52, 0x39, 0x19, 0xf3, 0x20, 0xd5, 0x3d, 0xa1,
	0xb6, 0x9d, 0xd3, 0x18, 0xc5, 0xed, 0x18, 0x9d, 0xfb, 0xd9, 0xd2, 0x45, 0xf3, 0xa5, 0x8b, 0xbe,
	0x97, 0x2e, 0xfa, 0x5c, 0xb9, 0xd6, 0x7c, 0xe5, 0x5a, 0x5f, 0x2b, 0xd7, 0xea, 0x5e, 0xf8, 0x81,
	0x1e, 0x8d, 0xfb, 0x64, 0xc0, 0x43, 0x3a, 0x8c, 0x43, 0x88, 0x54, 0xc0, 0xa3, 0x69, 0xfc, 0x4e,
	0x37, 0x5b, 0x9a, 0x03, 0xae, 0x42, 0xae, 0xe8, 0x34, 0xa9, 0xd5, 0x74, 0xda, 0xcf, 0x9b, 0xfa,
	0xce, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xe1, 0x79, 0x08, 0x29, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RemoteRouters) > 0 {
		for iNdEx := len(m.RemoteRouters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RemoteRouters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *GenesisRemoteRouterWrapper) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisRemoteRouterWrapper) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisRemoteRouterWrapper) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RemoteRouter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.TokenId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TokenId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Tokens) > 0 {
		for _, e := range m.Tokens {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RemoteRouters) > 0 {
		for _, e := range m.RemoteRouters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *GenesisRemoteRouterWrapper) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TokenId != 0 {
		n += 1 + sovGenesis(uint64(m.TokenId))
	}
	l = m.RemoteRouter.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, HypToken{})
			if err := m.Tokens[len(m.Tokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteRouters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteRouters = append(m.RemoteRouters, GenesisRemoteRouterWrapper{})
			if err := m.RemoteRouters[len(m.RemoteRouters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisRemoteRouterWrapper) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisRemoteRouterWrapper: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisRemoteRouterWrapper: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			m.TokenId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteRouter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemoteRouter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
